//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFM_MultiRender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-min -insecure -sfm_width 3840 -sfm_height 2160 -w 3840 -h 2160 +sv_lan 1 -sfm_st" +
            "artup_script \"G:\\video juegos\\SteamApps\\common\\SourceFilmmaker\\game\\workshop\\scr" +
            "ipts\\sfm\\mainmenu\\umfc\\Directional_Scale_Patch.py\"")]
        public string launchArgs {
            get {
                return ((string)(this["launchArgs"]));
            }
            set {
                this["launchArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\video juegos\\SteamApps\\common\\SourceFilmmaker\\game\\sfm.exe")]
        public string sfmExe {
            get {
                return ((string)(this["sfmExe"]));
            }
            set {
                this["sfmExe"] = value;
            }
        }
    }
}
